/**
 * Author : Yufei,T
 * Time : 8:53:18 AM
 * Description :
 */
package personal.tool.panel;

import java.awt.AWTException;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Point;
import java.awt.Window;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

import personal.tool.dialogue.SettingsDialogue;
import personal.tool.frame.SnapshotWindow;
import personal.tool.frame.StartFrame;

/**
 *
 * @author yufeitan
 */
public class ToolsbarPanel extends JPanel {

	/**
	 * Creates new form Toolsbarpanel
	 */
	public ToolsbarPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		newSnapshotButton = new JButton();

		newSnapshotButton.setText("New");
		newSnapshotButton.setToolTipText("");
		newSnapshotButton.setPreferredSize(new Dimension(70, 40));

		newSnapshotButton.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent evt) {
				newSnapshot(evt);
			}
		});
		add(newSnapshotButton);
		
		settingsButton = new JButton("Settings");
		settingsButton.setPreferredSize(new Dimension(70, 40));
		settingsButton.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent evt) {
				EventQueue.invokeLater(new Runnable() {
					public void run() {
						openSettingsDialogue(evt);
					}
				});
				
			}

			
		});
		add(settingsButton);

		
	}// </editor-fold>
	
	public void openSettingsDialogue(MouseEvent evt) {
		SettingsDialogue settingsDialogue = new SettingsDialogue();
		Point location = this.getLocationOnScreen();
		settingsDialogue.setLocation((int)location.getX(), (int)location.getY());
		settingsDialogue.setVisible(true);
	}

	private void newSnapshot(MouseEvent evt) {
//		getParent().getParent().getParent().getParent().setVisible(false);
		((JFrame)getParent().getParent().getParent().getParent()).dispose();
//		StartFrame.getInstance().setVisible(false);
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					Thread.sleep(500);
					new SnapshotWindow().setVisible(true);
				} catch (AWTException | InterruptedException e) {
					e.printStackTrace();
				}
			}
		});
	}

	// Variables declaration - do not modify
	private JButton newSnapshotButton;
	private JButton settingsButton;
	// End of variables declaration
}
