/**
 * Author : Yufei,T
 * Time : 4:42:53 PM
 * Description :
 */
package personal.tool.dialogue;

import java.awt.BorderLayout;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.WindowConstants;

import personal.tool.utils.GlobalSettings;

public class SettingsDialogue extends JDialog{

	 /**
     * Creates new form SettingsDialogue
     */
    public SettingsDialogue() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        modeComboBox = new JComboBox();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings Dialogue");

        modeComboBox.setModel(new DefaultComboBoxModel(new String[] { "Image Handle Mode", "Stay On Screen Mode" }));
        modeComboBox.setToolTipText("");
        
        if(GlobalSettings.getMode().equals("imageHandleMode"))
        	modeComboBox.setSelectedIndex(0);
        else
        	modeComboBox.setSelectedIndex(1);
        
        modeComboBox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                changeMode(modeComboBox.getSelectedIndex());
            }
        });
        getContentPane().add(modeComboBox, BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>                        

    private void changeMode(int selectedIndex) { 
    	if(selectedIndex == 0)
    		GlobalSettings.setMode("imageHandleMode");
    	else if(selectedIndex == 1)
    		GlobalSettings.setMode("stayOnScreenMode");
    }                                          


    // Variables declaration - do not modify                     
    private JComboBox modeComboBox;
    // End of variables declaration   
    
}

